### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/currency#1] opened 2021-11-28 16:03 UTC
Translation issues
Since a few commits those messages appear in the client console:

2020-03-19 21:42:44: ERROR[Main]: Ignoring empty translation for "@1 Minegeld cent coin"
@BuckarooBanzay

**Comment by BuckarooBanzay** [comment] 2021-11-29 16:08
I can't reproduce that, what minetest version? (i'm on 5.5.0-dev `bf3acbf38`)

**Comment by wsor4035** [comment] 2021-11-29 20:13
> I can't reproduce that, what minetest version? (i'm on 5.5.0-dev `bf3acbf38`)

i dunno, its your original issue that was ported over

**Comment by BuckarooBanzay** [comment] 2021-11-30 09:41
> i dunno, its your original issue that was ported over

Heh, in that case: closing :D

**Closed as completed by BuckarooBanzay** 2021-11-30 09:41 UTC
Labels: bug

**Comment by OgelGames** [comment] 2021-11-30 10:42
I think it's these:
https://github.com/mt-mods/currency/blob/f74ee653b8f8c60ea4f78e7dd827dcc568649dee/locale/currency.ru.tr#L18
https://github.com/mt-mods/currency/blob/f74ee653b8f8c60ea4f78e7dd827dcc568649dee/locale/currency.ms.tr#L18
